version: '2'

services:
  node:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    command: "bash -c \"npm install && npm start\""
    environment:
     - ENV=dev
     - PORT=8080
     - HOSTNAME=localhost
    volumes:
      - '.:/home/node/app'
    ports:
      - '8000:8080'
