version: '2'

services:
  nuit-info-2019:
    container_name: nuit-info-2019
    image: node:10-alpine
    user: "node"
    working_dir: /home/node/app
    command: "bash -c \"npm install && npm start\""
    environment:
     - ENV=dev
     - PORT=8080
     - HOSTNAME=localhost
    volumes:
      - '.:/home/node/app'
    labels:
      - "traefik.http.routers.nuit-info-2019.rule=Host(`nuitinfo.magicorp.fr`)"
      - traefik.http.routers.nuit-info-2019.middlewares=https-redirectscheme
      - traefik.http.services.nuit-info-2019.loadbalancer.server.port=8080
      - "traefik.http.routers.nuit-info-2019-secure.rule=Host(`nuitinfo.magicorp.fr`)"
      - traefik.http.routers.nuit-info-2019-secure.tls=true
      - traefik.http.routers.nuit-info-2019-secure.tls.certresolver=sslresolver
    networks:
      - backend

networks:
  backend:
    external:
      name: backend